version: '3.8'

services:
  clinicaltrials-api:
    image: clinicaltrials-api:latest
    build:
      context: .
      dockerfile: ./ClinicalTrials.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Server=db;Database=ClinicalTrialsDb;User=sa;Password=Administrator123!;TrustServerCertificate=True
    ports:
      - "5000:8080" 
      - "5001:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - clinicaltrials-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Administrator123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Administrator123! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clinicaltrials-network
    volumes:
      - sqldata:/var/opt/mssql

networks:
  clinicaltrials-network:
    driver: bridge

volumes:
  sqldata: