services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Administrator123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Administrator123!" -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - clinicaltrials-network

  api:
    image: clinicaltrials-api:latest
    build:
      context: .
      dockerfile: ClinicalTrials.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - clinicaltrials-network

networks:
  clinicaltrials-network:
    driver: bridge

volumes:
  sqldata: